/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenjualanReportPanel.java
 *
 * Created on 02 Agu 11, 10:05:13
 */
package com.retail.ui.report;

import com.retail.main.Main;
import com.retail.ui.main.FrameUtama;
import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Hauw
 */
public class PenjualanReportPanel extends javax.swing.JInternalFrame {

    /** Creates new form PenjualanReportPanel */
    public PenjualanReportPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aerithContentPanel1 = new aerith.swing.AerithContentPanel();
        aerithLabel1 = new aerith.swing.AerithLabel();
        aerithLabel2 = new aerith.swing.AerithLabel();
        jdcTanggalMulai = new com.toedter.calendar.JDateChooser();
        jdcTanggalSelesai = new com.toedter.calendar.JDateChooser();
        panelReport = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan Penjualan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        aerithLabel1.setText("Dari tanggal:");
        aerithLabel1.setFont(new java.awt.Font("Default", 1, 18));

        aerithLabel2.setText("Sampai tanggal:");
        aerithLabel2.setFont(new java.awt.Font("Default", 1, 18));

        jdcTanggalMulai.setDate(new java.util.Date());
        jdcTanggalMulai.setDateFormatString("dd-MM-yyyy"); // NOI18N

        jdcTanggalSelesai.setDate(new java.util.Date());
        jdcTanggalSelesai.setDateFormatString("dd-MM-yyyy"); // NOI18N

        panelReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laporan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelReport.setForeground(new java.awt.Color(255, 255, 255));
        panelReport.setOpaque(false);
        panelReport.setLayout(new java.awt.BorderLayout());

        buttonOk.setText("OK");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout aerithContentPanel1Layout = new org.jdesktop.layout.GroupLayout(aerithContentPanel1);
        aerithContentPanel1.setLayout(aerithContentPanel1Layout);
        aerithContentPanel1Layout.setHorizontalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, aerithContentPanel1Layout.createSequentialGroup()
                        .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(buttonOk)
                            .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, aerithLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, aerithLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                        .add(18, 18, 18)
                        .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jdcTanggalMulai, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .add(jdcTanggalSelesai, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(panelReport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
        aerithContentPanel1Layout.setVerticalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aerithLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jdcTanggalMulai, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aerithContentPanel1Layout.createSequentialGroup()
                        .add(aerithLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(buttonOk))
                    .add(jdcTanggalSelesai, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelReport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(aerithContentPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        FrameUtama.penjualanReportPanel = null;
        dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        Date tanggalMulai = jdcTanggalMulai.getDate();
        Date tanggalSelesai = jdcTanggalSelesai.getDate();
        if (tanggalMulai == null) {
            JOptionPane.showMessageDialog(this, "Anda belum memilih tanggal mulai", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (tanggalSelesai == null) {
            JOptionPane.showMessageDialog(this, "Anda belum memilih tanggal selesai", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            panelReport.removeAll();
            JasperPrint print = Main.getReportService().getReportPenjualan(tanggalMulai, tanggalSelesai);
            JRViewer viewer = new JRViewer(print);
            panelReport.add(viewer, BorderLayout.CENTER);
            panelReport.updateUI();
        }        
    }//GEN-LAST:event_buttonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aerith.swing.AerithContentPanel aerithContentPanel1;
    private aerith.swing.AerithLabel aerithLabel1;
    private aerith.swing.AerithLabel aerithLabel2;
    private javax.swing.JButton buttonOk;
    private com.toedter.calendar.JDateChooser jdcTanggalMulai;
    private com.toedter.calendar.JDateChooser jdcTanggalSelesai;
    private javax.swing.JPanel panelReport;
    // End of variables declaration//GEN-END:variables
}
