/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CalculatorPanel.java
 *
 * Created on 02 Agu 11, 3:24:24
 */
package com.retail.ui.transaksi;

import com.retail.main.Main;
import hauw.util.NumberValidator;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author Hauw
 */
public class CalculatorPanel extends javax.swing.JDialog {

    /** Creates new form CalculatorPanel */
    public CalculatorPanel(BigDecimal total) {
        super(Main.getFrameUtama(), true);
        initComponents();
        textTotal.setValue(total);
        setLocationRelativeTo(null);        
    }
    
    private void hitungKembali() {
        BigDecimal bayar = new BigDecimal(Double.parseDouble(textBayar.getText()));
        BigDecimal total = new BigDecimal(new Double(textTotal.getValue().toString()));
        if (bayar == null || bayar.compareTo(total) == -1) {
            JOptionPane.showMessageDialog(this, "Tolong periksa input bayar!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BigDecimal kembali = bayar.subtract(total);
            textKembali.setValue(kembali);
        }    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        darkgrayPanel1 = new paket.launk.java.container.DarkgrayPanel();
        panelOval1 = new paket.launk.java.container.PanelOval();
        aerithLabel1 = new aerith.swing.AerithLabel();
        aerithLabel2 = new aerith.swing.AerithLabel();
        textTotal = new paket.launk.java.controller.FormattedField();
        buttonHitung = new aerith.swing.AerithActionButton();
        aerithLabel3 = new aerith.swing.AerithLabel();
        textKembali = new paket.launk.java.controller.FormattedField();
        buttonKeluar = new aerith.swing.AerithActionButton();
        textBayar = new paket.launk.java.controller.OvalTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        darkgrayPanel1.setName("darkgrayPanel1"); // NOI18N
        darkgrayPanel1.setLayout(new java.awt.BorderLayout());

        panelOval1.setName("panelOval1"); // NOI18N

        aerithLabel1.setText("Bayar:");
        aerithLabel1.setName("aerithLabel1"); // NOI18N

        aerithLabel2.setText("Total Harga:");
        aerithLabel2.setName("aerithLabel2"); // NOI18N

        textTotal.setEditable(false);
        textTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        textTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textTotal.setName("textTotal"); // NOI18N

        buttonHitung.setText("HITUNG");
        buttonHitung.setName("buttonHitung"); // NOI18N
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        aerithLabel3.setText("Kembali:");
        aerithLabel3.setName("aerithLabel3"); // NOI18N

        textKembali.setEditable(false);
        textKembali.setCaretColor(new java.awt.Color(255, 255, 255));
        textKembali.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        textKembali.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textKembali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textKembali.setName("textKembali"); // NOI18N

        buttonKeluar.setText("KELUAR");
        buttonKeluar.setName("buttonKeluar"); // NOI18N
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        textBayar.setDocument(new NumberValidator(12, true));
        textBayar.setCaretColor(new java.awt.Color(255, 255, 255));
        textBayar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textBayar.setName("textBayar"); // NOI18N
        textBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOval1Layout = new javax.swing.GroupLayout(panelOval1);
        panelOval1.setLayout(panelOval1Layout);
        panelOval1Layout.setHorizontalGroup(
            panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval1Layout.createSequentialGroup()
                .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOval1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aerithLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(panelOval1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOval1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOval1Layout.createSequentialGroup()
                                .addComponent(aerithLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(panelOval1Layout.createSequentialGroup()
                                .addComponent(aerithLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addGap(23, 23, 23)))
                        .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(textKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))))
                .addContainerGap())
        );

        panelOval1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aerithLabel1, aerithLabel2});

        panelOval1Layout.setVerticalGroup(
            panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aerithLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panelOval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelOval1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aerithLabel1, aerithLabel2, textBayar, textTotal});

        darkgrayPanel1.add(panelOval1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(darkgrayPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        // TODO add your handling code here:
        hitungKembali();
    }//GEN-LAST:event_buttonHitungActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void textBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBayarActionPerformed
        // TODO add your handling code here:
        hitungKembali();
    }//GEN-LAST:event_textBayarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aerith.swing.AerithLabel aerithLabel1;
    private aerith.swing.AerithLabel aerithLabel2;
    private aerith.swing.AerithLabel aerithLabel3;
    private aerith.swing.AerithActionButton buttonHitung;
    private aerith.swing.AerithActionButton buttonKeluar;
    private paket.launk.java.container.DarkgrayPanel darkgrayPanel1;
    private paket.launk.java.container.PanelOval panelOval1;
    private paket.launk.java.controller.OvalTextField textBayar;
    private paket.launk.java.controller.FormattedField textKembali;
    private paket.launk.java.controller.FormattedField textTotal;
    // End of variables declaration//GEN-END:variables
}
