/*
 * To change this t

            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }mplate, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginPanel.java
 *
 * Created on 04 Agu 11, 6:08:28
 */

package com.retail.ui.security;

import com.retail.main.Main;
import com.retail.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Hauw
 */
public class LoginPanel extends javax.swing.JDialog {

    /** Creates new form LoginPanel */
    public LoginPanel() {
        super(Main.getFrameUtama(), true);
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateForm() {
        if(textUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "username masih kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if(textPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "password masih kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    public User login() {
        setVisible(true);
        String userName = textUsername.getText();
        char[] passwordChar = textPassword.getPassword();
        String password = "";
        for (char c : passwordChar) {
            password += c;
        }
        if(validateForm()) {
            if(Main.getUserService().checkLogin(userName, password)) {
                dispose();
                User user = Main.getUserService().getUser(userName);
                return user;
            } else {
                JOptionPane.showMessageDialog(this, "login gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            }            
        }
        return null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aerithContentPanel1 = new aerith.swing.AerithContentPanel();
        aerithLabel1 = new aerith.swing.AerithLabel();
        aerithLabel2 = new aerith.swing.AerithLabel();
        textPassword = new paket.launk.java.controller.OvalPasswordField();
        textUsername = new paket.launk.java.controller.OvalTextField();
        buttonLogin = new aerith.swing.AerithActionButton();
        buttonBatal = new aerith.swing.AerithActionButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        aerithLabel1.setText("username :");
        aerithLabel1.setFont(new java.awt.Font("Default", 1, 18)); // NOI18N

        aerithLabel2.setText("password :");
        aerithLabel2.setFont(new java.awt.Font("Default", 1, 18)); // NOI18N

        textPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        textPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });

        textUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        textUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonLogin.setText("Login");
        buttonLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonBatal.setText("Batal");
        buttonBatal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout aerithContentPanel1Layout = new org.jdesktop.layout.GroupLayout(aerithContentPanel1);
        aerithContentPanel1.setLayout(aerithContentPanel1Layout);
        aerithContentPanel1Layout.setHorizontalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aerithContentPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(aerithLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(textPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(textUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .add(aerithContentPanel1Layout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(buttonLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(38, 38, 38)
                        .add(buttonBatal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        aerithContentPanel1Layout.setVerticalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(aerithLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(aerithLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonBatal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(aerithContentPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_textPasswordActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_buttonLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aerith.swing.AerithContentPanel aerithContentPanel1;
    private aerith.swing.AerithLabel aerithLabel1;
    private aerith.swing.AerithLabel aerithLabel2;
    private aerith.swing.AerithActionButton buttonBatal;
    private aerith.swing.AerithActionButton buttonLogin;
    private paket.launk.java.controller.OvalPasswordField textPassword;
    private paket.launk.java.controller.OvalTextField textUsername;
    // End of variables declaration//GEN-END:variables

}
