/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeranjangPanel.java
 *
 * Created on 02 Agu 11, 2:00:20
 */
package com.retail.ui.toolbar;

import paket.launk.java.controller.MenuButton;

/**
 *
 * @author Hauw
 */
public class KeranjangPanel extends javax.swing.JPanel {

    /** Creates new form KeranjangPanel */
    public KeranjangPanel() {
        initComponents();
    }

    public MenuButton getButtonBatal() {
        return buttonBatal;
    }

    public MenuButton getButtonEditKeranjang() {
        return buttonEditKeranjang;
    }

    public MenuButton getButtonHapusKeranjang() {
        return buttonHapusKeranjang;
    }

    public MenuButton getButtonTambahKeranjang() {
        return buttonTambahKeranjang;
    }

    public void kondisiAwal() {
        buttonTambahKeranjang.setEnabled(true);
        buttonEditKeranjang.setEnabled(false);
        buttonHapusKeranjang.setEnabled(false);
        buttonBatal.setEnabled(false);        
    }
    
    public void kondisiUbahOrHapus() {
        buttonTambahKeranjang.setEnabled(false);
        buttonEditKeranjang.setEnabled(true);
        buttonHapusKeranjang.setEnabled(true);
        buttonBatal.setEnabled(true);    
    }

    public void enableForm(boolean status) {
        buttonTambahKeranjang.setEnabled(status);
        buttonEditKeranjang.setEnabled(status);
        buttonHapusKeranjang.setEnabled(status);
        buttonBatal.setEnabled(status);    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBatal = new paket.launk.java.controller.MenuButton();
        buttonHapusKeranjang = new paket.launk.java.controller.MenuButton();
        buttonEditKeranjang = new paket.launk.java.controller.MenuButton();
        buttonTambahKeranjang = new paket.launk.java.controller.MenuButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Keranjang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        setOpaque(false);

        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        buttonBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonBatal.setName("buttonBatal"); // NOI18N

        buttonHapusKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_remove.png"))); // NOI18N
        buttonHapusKeranjang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonHapusKeranjang.setName("buttonHapusKeranjang"); // NOI18N

        buttonEditKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_edit.png"))); // NOI18N
        buttonEditKeranjang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonEditKeranjang.setName("buttonEditKeranjang"); // NOI18N

        buttonTambahKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_add.png"))); // NOI18N
        buttonTambahKeranjang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTambahKeranjang.setName("buttonTambahKeranjang"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonTambahKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEditKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonHapusKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonTambahKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHapusKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private paket.launk.java.controller.MenuButton buttonBatal;
    private paket.launk.java.controller.MenuButton buttonEditKeranjang;
    private paket.launk.java.controller.MenuButton buttonHapusKeranjang;
    private paket.launk.java.controller.MenuButton buttonTambahKeranjang;
    // End of variables declaration//GEN-END:variables
}
