/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on 06 Agu 11, 2:18:28
 */

package com.retail.ui.about;

import com.retail.main.Main;

/**
 *
 * @author Hauw
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog() {
        super(Main.getFrameUtama(), true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aerithContentPanel1 = new aerith.swing.AerithContentPanel();
        aerithLabel1 = new aerith.swing.AerithLabel();
        labelImage = new javax.swing.JLabel();
        aerithLabel2 = new aerith.swing.AerithLabel();
        aerithLabel3 = new aerith.swing.AerithLabel();
        aerithLabel4 = new aerith.swing.AerithLabel();
        aerithLabel5 = new aerith.swing.AerithLabel();
        aerithLabel6 = new aerith.swing.AerithLabel();
        aerithLabel7 = new aerith.swing.AerithLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tentang Aplikasi");
        setResizable(false);

        aerithLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aerithLabel1.setText("Azzwars Point Of Sales");
        aerithLabel1.setVerifyInputWhenFocusTarget(false);

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azzwars.jpeg"))); // NOI18N

        aerithLabel2.setText("Develop & Customize by:");
        aerithLabel2.setFont(new java.awt.Font("Default", 1, 14)); // NOI18N

        aerithLabel3.setText("Thaks to :");
        aerithLabel3.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel4.setText("yulias.hauw@gmail.com");
        aerithLabel4.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel5.setText("Tarsidi");
        aerithLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N

        aerithLabel6.setText("github.com, zxing, code.google.com");
        aerithLabel6.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel7.setText("Bartosz Firyn (sarXos)");
        aerithLabel7.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        org.jdesktop.layout.GroupLayout aerithContentPanel1Layout = new org.jdesktop.layout.GroupLayout(aerithContentPanel1);
        aerithContentPanel1.setLayout(aerithContentPanel1Layout);
        aerithContentPanel1Layout.setHorizontalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aerithLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(aerithContentPanel1Layout.createSequentialGroup()
                        .add(labelImage)
                        .add(18, 18, 18)
                        .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(aerithLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(aerithLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aerithContentPanel1Layout.setVerticalGroup(
            aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aerithContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(aerithLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(aerithContentPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelImage)
                    .add(aerithContentPanel1Layout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(aerithLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(aerithLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(aerithLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(aerithLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(aerithLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(aerithLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(aerithContentPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aerith.swing.AerithContentPanel aerithContentPanel1;
    private aerith.swing.AerithLabel aerithLabel1;
    private aerith.swing.AerithLabel aerithLabel2;
    private aerith.swing.AerithLabel aerithLabel3;
    private aerith.swing.AerithLabel aerithLabel4;
    private aerith.swing.AerithLabel aerithLabel5;
    private aerith.swing.AerithLabel aerithLabel6;
    private aerith.swing.AerithLabel aerithLabel7;
    private javax.swing.JLabel labelImage;
    // End of variables declaration//GEN-END:variables

}
